### ISSUE TITLE
Fix a bug in the Branching Ratios Plot

### ISSUE THREAD

**Issue by fbientrigo** [fbientrigo/dihiggs#7]
# Discrepancy in H₂ Branching Ratios between Plot and CalcPhys Output

**Description**  
I’ve noticed that the branching-ratio plot generated by our batch routine does not match the values produced by the standalone CalcPhys tool. For example, at the physical point:

```yaml
m_phi:        200.0
m_A:          300.00073
sin_ba:       1.0
tan_beta:     10000.0
lambda_6:     0.1
lambda_7:     0.0
m12_2:        3.999909
positivity_ok:    1
unitarity_ok:     1
perturbativity_ok:1
w_h2_bb:      0.0
w_h2_tautau:  0.0
w_h2_vv:      [1.2638e-10, 0.0, 0.0]
w_h2_gaga:    0.0
w_h2_Zga:     0.0
…
branching_ratio_h2_gaga: 0.68332
````

—but when invoking CalcPhys directly:

```bash
$ ./CalcPhys 125 200 300 300 1 0.1 0 3.9999089999999904 10000 1.0 punto200.lhe
```

we get:

```
Decay table for H
Total width:   1.848e-10 GeV      BR
H → γ γ    1.263e-10   0.6833
H → Z γ     5.853e-11   0.3167
```

**Observed Behavior**

* Plot data (`w_h2_gaga`, `w_h2_Zga`) are zero.
* Plot’s `w_h2_bb` and `w_h2_tautau` are incorrectly zero, though CalcPhys shows non-zero partial widths.

**Expected Behavior**

* Partial widths and branching ratios in the plot should exactly match CalcPhys output:

  * `w_h2_gaga` ≃ 1.2638×10⁻¹⁰
  * `w_h2_Zga` ≃ 5.8572×10⁻¹¹
  * `w_h2_bb` and `w_h2_tautau` should reflect the non-zero widths seen in CalcPhys.

**Steps to Reproduce**

1. Run batch calculation with

   ```python
   physpoint(200, 3.9999089999999904, 300, 1, 10000)
   ```
2. Inspect returned dict:

   ```python
   {
     'w_h2_bb':   0.0,
     'w_h2_tautau': 0.0,
     'w_h2_gaga': 1.2638e-10,
     'w_h2_Zga':  5.8572e-11,
     …  
   }
   ```
3. Plot these values in the branching-ratio plot.
4. Run CalcPhys as above and compare the “Decay table for H”.

**Additional Context**

* This discrepancy appears only when using our optimized “batch” interface.
* Single-point calls to `./CalcPhys` yield the correct values.
* I suspect that either the unpacking logic for `w_h2_*` in the batch routine or the mapping between particle IDs and widths is not handling some channels correctly.

**Suggested Investigation Areas**

* Verify that the batch wrapper correctly parses and assigns all partial widths (especially for `b` and `τ` channels).
* Confirm the mapping from PDG IDs to plot series (e.g. ID 5 → `bb`, ID 15 → `tautau`, ID 22 → `gaga`, ID 23→ `Zga`).
* Add a unit-test comparing single‐point CalcPhys output to batch output for all decay channels.

**Screenshots / Logs**
![Branching plot vs. CalcPhys output](https://github.com/user-attachments/assets/5a42ceb6-0c02-4c52-b2fa-b39b0d9eb374)
